In [1]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [2]:
non_local_df = pd.read_csv('./data/topic-results/result_non_local.csv')[['idx', 'label']]

In [3]:
# 1.构造事务数据
transactions = (
    non_local_df["label"]
    .dropna()
    .astype(str)
    .apply(lambda x: [i.strip() for i in x.split("@") if i.strip()])
    .tolist()
)

# 2.one-hot 编码
te = TransactionEncoder()
te_ary = te.fit(transactions).transform(transactions)
df_trans = pd.DataFrame(te_ary, columns=te.columns_)

# 3.频繁项集
frequent_itemsets = apriori(df_trans, min_support=0.01, use_colnames=True)
frequent_itemsets["length"] = frequent_itemsets["itemsets"].apply(len)
frequent_itemsets = frequent_itemsets.sort_values(["length", "support"], ascending=[True, False])

print("频繁项集：")
frequent_itemsets.head(30)

频繁项集：

     support                       itemsets  length
5   0.423095             frozenset({政治与政策})       1
7   0.230716             frozenset({文化与旅游})       1
12  0.210037             frozenset({经济与金融})       1
0   0.144981           frozenset({交通与基础设施})       1
8   0.124768           frozenset({民生与便民服务})       1
3   0.096887           frozenset({医疗与公共健康})       1
6   0.079693             frozenset({教育与人才})       1
2   0.053671                frozenset({其他})       1
11  0.033225             frozenset({科技与创新})       1
9   0.032993           frozenset({法律与治安管理})       1
1   0.030437              frozenset({体育赛事})       1
4   0.029972             frozenset({就业与培训})       1
10  0.010455          frozenset({环境与可持续发展})       1
25  0.082249      frozenset({经济与金融, 政治与政策})       2
30  0.066682      frozenset({文化与旅游, 经济与金融})       2
16  0.057388  frozenset({交通与基础设施, 民生与便民服务})       2
23  0.039266      frozenset({文化与旅游, 政治与政策})       2
17  0.035548    frozenset({交通与基础设施, 经济与金融})       2
24  0.034851    frozenset({民生与便民服务, 政治与政策})       2
15  0.024164    frozenset({文化与旅游, 交通与基础设施})       2
13  0.023002  frozenset({交通与基础设施, 医疗与公共健康})       2
31  0.022305    frozenset({经济与金融, 民生与便民服务})       2
28  0.021840      frozenset({教育与人才, 经济与金融})       2
18  0.019749  frozenset({民生与便民服务, 医疗与公共健康})       2
26  0.019052      frozenset({文化与旅游, 教育与人才})       2
14  0.016961    frozenset({交通与基础设施, 政治与政策})       2
32  0.016729      frozenset({科技与创新, 经济与金融})       2
22  0.016496      frozenset({教育与人才, 政治与政策})       2
19  0.013011    frozenset({经济与金融, 医疗与公共健康})       2
21  0.012546      frozenset({经济与金融, 就业与培训})       2

In [4]:
# 4.关联规则
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.3)
rules = rules.sort_values(["lift", "confidence"], ascending=False)

print("关联规则：")
rules[["antecedents", "consequents", "support", "confidence", "lift"]].head(20)

关联规则：

,antecedents,consequents,support,confidence,lift
7,frozenset({就业与培训}),frozenset({教育与人才}),0.010223,0.341085,4.279974
12,"frozenset({民生与便民服务, 医疗与公共健康})",frozenset({交通与基础设施}),0.011849,0.600000,4.138462
11,"frozenset({交通与基础设施, 医疗与公共健康})",frozenset({民生与便民服务}),0.011849,0.515152,4.128887
6,frozenset({科技与创新}),frozenset({教育与人才}),0.010455,0.314685,3.948704
14,"frozenset({经济与金融, 民生与便民服务})",frozenset({交通与基础设施}),0.011617,0.520833,3.592415
3,frozenset({民生与便民服务}),frozenset({交通与基础设施}),0.057388,0.459963,3.172564
2,frozenset({交通与基础设施}),frozenset({民生与便民服务}),0.057388,0.395833,3.172564
9,"frozenset({文化与旅游, 政治与政策})",frozenset({经济与金融}),0.025790,0.656805,3.127088
13,"frozenset({交通与基础设施, 经济与金融})",frozenset({民生与便民服务}),0.011617,0.326797,2.619248
4,frozenset({科技与创新}),frozenset({经济与金融}),0.016729,0.503497,2.397178
5,frozenset({就业与培训}),frozenset({经济与金融}),0.012546,0.418605,1.993003
1,frozenset({经济与金融}),frozenset({文化与旅游}),0.066682,0.317478,1.376057
10,"frozenset({经济与金融, 政治与政策})",frozenset({文化与旅游}),0.025790,0.313559,1.359073
0,frozenset({经济与金融}),frozenset({政治与政策}),0.082249,0.391593,0.925544
8,"frozenset({文化与旅游, 经济与金融})",frozenset({政治与政策}),0.025790,0.386760,0.914120

In [5]:
print("2项集：")
frequent_itemsets[frequent_itemsets["length"] == 2].sort_values("support", ascending=False)

2项集：

     support                       itemsets  length
25  0.082249      frozenset({经济与金融, 政治与政策})       2
30  0.066682      frozenset({文化与旅游, 经济与金融})       2
16  0.057388  frozenset({交通与基础设施, 民生与便民服务})       2
23  0.039266      frozenset({文化与旅游, 政治与政策})       2
17  0.035548    frozenset({交通与基础设施, 经济与金融})       2
24  0.034851    frozenset({民生与便民服务, 政治与政策})       2
15  0.024164    frozenset({文化与旅游, 交通与基础设施})       2
13  0.023002  frozenset({交通与基础设施, 医疗与公共健康})       2
31  0.022305    frozenset({经济与金融, 民生与便民服务})       2
28  0.021840      frozenset({教育与人才, 经济与金融})       2
18  0.019749  frozenset({民生与便民服务, 医疗与公共健康})       2
26  0.019052      frozenset({文化与旅游, 教育与人才})       2
14  0.016961    frozenset({交通与基础设施, 政治与政策})       2
32  0.016729      frozenset({科技与创新, 经济与金融})       2
22  0.016496      frozenset({教育与人才, 政治与政策})       2
19  0.013011    frozenset({经济与金融, 医疗与公共健康})       2
21  0.012546      frozenset({经济与金融, 就业与培训})       2
29  0.012546    frozenset({文化与旅游, 民生与便民服务})       2
27  0.010455      frozenset({科技与创新, 教育与人才})       2
20  0.010223      frozenset({教育与人才, 就业与培训})       2

In [6]:
print("3项集：")
frequent_itemsets[frequent_itemsets["length"] == 3].sort_values("support", ascending=False)

3项集：

     support                                itemsets  length
35  0.025790        frozenset({文化与旅游, 经济与金融, 政治与政策})       3
33  0.011849  frozenset({交通与基础设施, 民生与便民服务, 医疗与公共健康})       3
34  0.011617    frozenset({经济与金融, 交通与基础设施, 民生与便民服务})       3