In [58]:
import pandas as pd

In [59]:
df_local = pd.read_excel('./analysis-data/local_topic-freq.xlsx')
df_local['source'] = 'Local'
df_non = pd.read_excel('./analysis-data/non_topic-freq.xlsx')
df_non['source'] = 'Non-local'

In [60]:
local_rank = df_local.copy()
non_rank = df_non.copy()

In [61]:
local_rank = local_rank.sort_values('freq', ascending=False).reset_index(drop=True)
local_rank['rank_local'] = local_rank.index + 1

In [62]:
local_rank

       topic  freq      topic_en source  rank_local
0      文化与旅游   665       Culture  Local           1
1      经济与金融   593       Economy  Local           2
2    医疗与公共健康   545        Health  Local           3
3    民生与便民服务   403    Livelihood  Local           4
4      政治与政策   308      Politics  Local           5
5    交通与基础设施   207     Transport  Local           6
6      就业与培训   193    Employment  Local           7
7      教育与人才   154  Edu & Talent  Local           8
8      应急与安全   123        Safety  Local           9
9    法律与治安管理   122           Law  Local          10
10  环境与可持续发展   121   Environment  Local          11
11     科技与创新    87       Science  Local          12
12      体育赛事    70        Sports  Local          13
13        其他     4        Others  Local          14

In [63]:
non_rank = non_rank.sort_values('freq', ascending=False).reset_index(drop=True)
non_rank['rank_non'] = non_rank.index + 1

In [64]:
non_rank

       topic  freq      topic_en     source  rank_non
0      政治与政策  1821      Politics  Non-local         1
1      文化与旅游   993       Culture  Non-local         2
2      经济与金融   904       Economy  Non-local         3
3    交通与基础设施   624     Transport  Non-local         4
4    民生与便民服务   537    Livelihood  Non-local         5
5    医疗与公共健康   417        Health  Non-local         6
6      教育与人才   343  Edu & Talent  Non-local         7
7         其他   231        Others  Non-local         8
8      科技与创新   143       Science  Non-local         9
9    法律与治安管理   142           Law  Non-local        10
10      体育赛事   131        Sports  Non-local        11
11     就业与培训   129    Employment  Non-local        12
12  环境与可持续发展    45   Environment  Non-local        13
13     应急与安全    38        Safety  Non-local        14

In [65]:
local_rank = local_rank[["topic_en", "topic", "freq", "rank_local"]]
non_rank = non_rank[["topic_en", "topic", "freq", "rank_non"]]
df_rank_compare = pd.merge(
    local_rank,
    non_rank,
    on='topic_en',
    how='outer',
    suffixes=('_local', '_non')
)

In [66]:
df_rank_compare

,topic_en,topic_local,freq_local,rank_local,topic_non,freq_non,rank_non
0,Culture,文化与旅游,665,1,文化与旅游,993,2
1,Economy,经济与金融,593,2,经济与金融,904,3
2,Health,医疗与公共健康,545,3,医疗与公共健康,417,6
3,Livelihood,民生与便民服务,403,4,民生与便民服务,537,5
4,Politics,政治与政策,308,5,政治与政策,1821,1
5,Transport,交通与基础设施,207,6,交通与基础设施,624,4
6,Employment,就业与培训,193,7,就业与培训,129,12
7,Edu & Talent,教育与人才,154,8,教育与人才,343,7
8,Safety,应急与安全,123,9,应急与安全,38,14
9,Law,法律与治安管理,122,10,法律与治安管理,142,10
10,Environment,环境与可持续发展,121,11,环境与可持续发展,45,13
11,Science,科技与创新,87,12,科技与创新,143,9
12,Sports,体育赛事,70,13,体育赛事,131,11
13,Others,其他,4,14,其他,231,8

In [67]:
df_rank_compare['rank_diff'] = df_rank_compare['rank_local'] - df_rank_compare['rank_non']

In [68]:
df_rank_compare['abs_rank_diff'] = df_rank_compare['rank_diff'].abs()

In [70]:
df_rank_compare = df_rank_compare.sort_values('abs_rank_diff', ascending=False)
df_rank_compare

,topic_en,topic_local,freq_local,rank_local,topic_non,freq_non,rank_non,rank_diff,abs_rank_diff
13,Others,其他,4,14,其他,231,8,6,6
6,Employment,就业与培训,193,7,就业与培训,129,12,-5,5
8,Safety,应急与安全,123,9,应急与安全,38,14,-5,5
4,Politics,政治与政策,308,5,政治与政策,1821,1,4,4
2,Health,医疗与公共健康,545,3,医疗与公共健康,417,6,-3,3
11,Science,科技与创新,87,12,科技与创新,143,9,3,3
5,Transport,交通与基础设施,207,6,交通与基础设施,624,4,2,2
10,Environment,环境与可持续发展,121,11,环境与可持续发展,45,13,-2,2
12,Sports,体育赛事,70,13,体育赛事,131,11,2,2
0,Culture,文化与旅游,665,1,文化与旅游,993,2,-1,1
1,Economy,经济与金融,593,2,经济与金融,904,3,-1,1
3,Livelihood,民生与便民服务,403,4,民生与便民服务,537,5,-1,1
7,Edu & Talent,教育与人才,154,8,教育与人才,343,7,1,1
9,Law,法律与治安管理,122,10,法律与治安管理,142,10,0,0

In [80]:
def output_rank(localdf, nondf):
    local = localdf.copy()
    non = nondf.copy()
   
    local = local.sort_values('freq', ascending=False).reset_index(drop=True)
    local['RANK'] = local.index + 1

    non = non.sort_values('freq', ascending=False).reset_index(drop=True)
    non['RANK'] = non.index + 1

    temp = pd.concat([local, non])
    temp[['topic_en', 'source', 'RANK']].to_excel('./analysis-data/topic_rank_diff.xlsx', index=None)
    return temp

In [81]:
output_rank(df_local, df_non)

       topic  freq      topic_en     source  RANK
0      文化与旅游   665       Culture      Local     1
1      经济与金融   593       Economy      Local     2
2    医疗与公共健康   545        Health      Local     3
3    民生与便民服务   403    Livelihood      Local     4
4      政治与政策   308      Politics      Local     5
5    交通与基础设施   207     Transport      Local     6
6      就业与培训   193    Employment      Local     7
7      教育与人才   154  Edu & Talent      Local     8
8      应急与安全   123        Safety      Local     9
9    法律与治安管理   122           Law      Local    10
10  环境与可持续发展   121   Environment      Local    11
11     科技与创新    87       Science      Local    12
12      体育赛事    70        Sports      Local    13
13        其他     4        Others      Local    14
0      政治与政策  1821      Politics  Non-local     1
1      文化与旅游   993       Culture  Non-local     2
2      经济与金融   904       Economy  Non-local     3
3    交通与基础设施   624     Transport  Non-local     4
4    民生与便民服务   537    Livelihood  Non-local     5
5    医疗与公共健康   417        Health  Non-local     6
6      教育与人才   343  Edu & Talent  Non-local     7
7         其他   231        Others  Non-local     8
8      科技与创新   143       Science  Non-local     9
9    法律与治安管理   142           Law  Non-local    10
10      体育赛事   131        Sports  Non-local    11
11     就业与培训   129    Employment  Non-local    12
12  环境与可持续发展    45   Environment  Non-local    13
13     应急与安全    38        Safety  Non-local    14